### ISSUE TITLE
Animated Banners via Standard Texture

### ISSUE THREAD

**Issue by justalemon** [LemonUIbyLemon/LemonUI#102]
An animated banner is a banner where the image changes every frame, creating an animation.

For example, there are 60 textures in animation.ytd, called animation_0 to animation_59, representing 60 frames for a total of 1 second.

You then just set up a banner with a total of 60 frames and a duration of 1 second with ytd called animation and LemonUI does all of the work.

**Comment by LiuXin097** [comment]
![捕获](https://user-images.githubusercontent.com/50867544/234545699-cc56a696-b7b2-4f2b-8ddf-80233999ac0a.PNG)
Is this one?

**Comment by justalemon** [comment]
Nop, just a custom system to use a single YTD to create an animation that changes over time.

**Comment by LiuXin097** [comment]
![捕获](https://user-images.githubusercontent.com/50867544/234546855-66d45dee-aac7-4afb-beb0-cb156c9f1806.PNG)
In a later update, you can add this？

**Comment by justalemon** [comment]
I have tried to add it. It's complicated to do so.
