### ISSUE TITLE
Submenu items use Menu.subtitle instead of Menu.title for the generated MenuItem

### ISSUE THREAD

**Issue by jaymirecki** [LemonUIbyLemon/LemonUI#113]
When you add a submenu, the item created in the parent menu uses the submenu's subtitle as the item's title (rather than the submenu's title, which I had assumed was used).

This seems like an intentional choice, but it was confusing to me at first (especially when I'm lazy and don't give a submenu a subtitle). Could we document this be documented more explicitly? Here's the code: https://github.com/LemonUIbyLemon/LemonUI/blob/master/LemonUI/Menus/NativeSubmenuItem.cs#L35

**Comment by justalemon** [comment]
The API of LemonUI is based on a subset of the NativeUI API, which does indeed uses Title for the banner text.

https://github.com/Guad/NativeUI/blob/1c6bfd48a6bce610acbec687a67b08d3c533ac64/NativeUI/UIMenu.cs#L220

I will probably end up marking Title as deprecated and create a new property called BannerText with the same usage and purpose.

**Comment by justalemon** [comment]
Ill keep this open so can remember to update the description of both properties.

**Comment by justalemon** [comment]
Title is now BannerText
Subtitle is now Name
SubtitleBehavior is now NameBehavior

**Comment by justalemon** [comment]
Update: SubtitleBehavior is now HeaderBehavior
