### ISSUE TITLE
MissingMethodException when returning NativeMenu.Name or NativeMenu.BannerText

### ISSUE THREAD

**Issue by dppls** [LemonUIbyLemon/LemonUI#128]
Hey,
I'm always getting a MissingMethodException when trying to return a NativeMenu's Name or BannerText.

The code throwing the exception looks like this (I've already reduced it to the bare minimum, to determine what was causing the exception)

```
NativeMenu mainmenu = new NativeMenu("EcoPloos", "Main Menu");  // is added to ObjectPool on CreateMenu()
public string ReturnActiveMenu() {  // function is called when OnKeyDown Keys.Enter
   int cnt = 0;
   string activeMenuName = "404";

   try {
      activeMenuName = mainmenu.Name;  // removing this line is fixing the exception, same behaviour with mainmenu.BannerText
      Notification.Show($"You're at {activeMenuName} ({cnt})");
   } catch (Exception ex) {
      Notification.Show("Oopsie :/ \n\n" + ex.Message);
   }
   return activeMenuName;
}
```

The script throws the MissingMethodException but it's being catched outside of my try-catch, notice the Notification looking different to what I declared:
![grafik](https://github.com/LemonUIbyLemon/LemonUI/assets/6112455/113d8a5a-937d-4c55-839d-a05ab1d5cc18)

Same behaviour when calling BannerText but Description works fine.

Any help is very much appreciated - I'm just trying to figure out, where in the menu or submenus the player actually is.

**Comment by justalemon** [comment]
What does your stack trace says?

**Comment by justalemon** [comment]
You have an outdated version of LemonUI. You are using in your Visual Studio/Rider project version 1.10 but your GTA V folder has 1.9.4 or older.

**Comment by dppls** [comment]
that's it, I had to manually change the lemonui version in NuGet to 1.9.4.

Working now, thank you so much!
