### ISSUE TITLE
2 shvdn2

### ISSUE THREAD

**Issue by Michael21107** [LemonUIbyLemon/LemonUI#130]
there are 2 svhvdn2 here, i think the second should be 3
![image](https://github.com/LemonUIbyLemon/LemonUI/assets/121039033/86bf1af7-b86f-4c9c-9b6a-e62de7518311)
https://github.com/LemonUIbyLemon/LemonUI#scripthookvdotnet-2-and-scripthookvdotnet-3

**Comment by justalemon** [comment]
Thanks!
