### ISSUE TITLE
Typo in parameter of NativeMenu constructor

### ISSUE THREAD

**Issue by WithLithum** [LemonUIbyLemon/LemonUI#166]
![image](https://github.com/LemonUIbyLemon/LemonUI/assets/37800788/98467231-7e79-407f-865d-9403aec18e52)

- Expected: bannerText
- Actual: b*q*nnerText

### Environment

- Version: SHVDN3, 2.0.0

### Note

I don't think this can be fixed without a breaking change considering this made it into the release.

**Comment by justalemon** [comment]
Fixed by #171
