### ISSUE TITLE
Menu items should have different look when being hovered

### ISSUE THREAD

**Issue by WithLithum** [LemonUIbyLemon/LemonUI#20]
Sorry if title is incorrect.

But anyway, here is the comparison:
![Grand Theft Auto V 2021_6_14 16_03_35](https://user-images.githubusercontent.com/37800788/121859698-9d852000-cd2a-11eb-92f4-712ea60ab2c0.png)
![Grand Theft Auto V 2021_6_14 16_04_21](https://user-images.githubusercontent.com/37800788/121859794-bab9ee80-cd2a-11eb-9361-217773f490e3.png)

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/159832765-173cf70f-1417-494a-bc34-f3d0934d3adb.png)
