### ISSUE TITLE
Add option to change colors of foreground bars for NativeStatsInfo

### ISSUE THREAD

**Issue by SkyZ0347** [LemonUIbyLemon/LemonUI#60]
I'll suggest adding options to make struct with set colors that represent sp characters, like
Michael has #65B4D4
Franklin has #ABEDAB
Trevor has #FFA357
Gta online character i think has darker blue #2D6EB9 or white.
But still give option to set from RGB.

**Comment by justalemon** [comment]
Implemented in 882f36fcd442cdd7362c7b2cbc648c0514adb4e7
