### ISSUE TITLE
Change color of banner | rproblem

### ISSUE THREAD

**Issue by gameplayoffert** [LemonUIbyLemon/LemonUI#62]
Hi, i tried to change the "Banner" of a NativeMenu with this : **new_menu.Banner.Color = Color.FromArgb(255,0,0);** but i get a Dark Red color instead of a Red so why ? Sadly there is no documentation about how to do it so is it a bug ?

**Comment by justalemon** [comment]
Because it adds the color on top of the banner, which is a dark blue.

**Comment by gameplayoffert** [comment]
oh ok but what i need to do then ?

**Comment by justalemon** [comment]
You could either:

- Change the texture of the banner
- Make your own texture for the banner
- Change the banner from a texture to a rectangle

**Comment by gameplayoffert** [comment]
oh ok but i have an other question. How can i change the texture of the banner ? It's where exactly ? and otherwise what i need to change to get a rectangle instead of a texture ?

**Comment by justalemon** [comment]
> How can i change the texture of the banner ?

You change the Dictionary and Texture properties of the Banner. You need to cast it to a ScaledTexture first.

> and otherwise what i need to change to get a rectangle instead of a texture ?

You set a new banner from ScaledRectangle.

**Comment by gameplayoffert** [comment]
oh ok thank you i will try then

**Comment by justalemon** [comment]
If you have any further questions, feel free to reopen the issue or join the Discord server at https://discord.gg/Cf6sspj
