### ISSUE TITLE
There is no way to prevent the subtitle from being drawn

### ISSUE THREAD

**Issue by KimTisott** [LemonUIbyLemon/LemonUI#66]
The subtitle background is always drawn, even when the text is empty. Current API does not provide a mechanism to hide it completely.

![image](https://user-images.githubusercontent.com/40810123/172625523-ef45d4d7-6ed3-4aeb-aae8-26d6d9a19b46.png)

**Comment by KimTisott** [comment]
@justalemon

I see three possible solutions:

1. Add a master SubtitleVisible property to control both image and text rendering;
2. Render image and text separately - and text only if not empty;
3. Expose SubtitleImage property to allow manual removal of the entire subtitle;

What would you suggest? I will submit a PR.

**Comment by justalemon** [comment]
What do you mean with subtitle? Because the subtitle is the white text on a black background.

**Comment by KimTisott** [comment]
> What do you mean with subtitle?

The white text on a black background right under the title. In the image, 'Player' is not the subtitle, it's the first item of the menu. The subtitle background renders even when there is no subtitle nor item count.

**Comment by justalemon** [comment]
# OH

I see it now.

In that case, to give more customization options, I would suggest an enum like SubtitleBehavior where it defines the behavior of the subtitle to 3 possible styles:

1. Always show the background even if is empty, which should be the default (AlwaysShow = 0)
2. Hide when there is no text, show when there is some (HideOnEmpty = 1)
3. Always hide the subtitle and it's background (AlwaysHide = 2)

**Comment by justalemon** [comment]
I feel that it will complement CountVisibility to be honest.

With the Flag enums and Subtitle object, those would be a breaking changes which is not something I would like (NativeUI had some nasty breaking changes almost every single release before I helped with the most recent releases, and I wouldn't like to see that again).
