### ISSUE TITLE
Closing Menu on Gamepad Trigers Other Actions

### ISSUE THREAD

**Issue by 07-stadia** [LemonUIbyLemon/LemonUI#72]
**Issue:**
When in any type of vehicle, closing the menu using a gamepad (B button), also activates the associated action, this case the cinematic camera.
**Expected behavior:**
When closing the menu using gamepad, not activating any actions other then closing the menu.
**Environment Information**
LemonUI version: 1.7.0
RagePluginHookSDK: 1.86.1288.16169
.NET Framework: 4.7.2

**Comment by justalemon** [comment]
I feel that this one is related to #10.

Because this is a little thing that does no big harm, I will leave it for later once I figure it out.

**Comment by 07-stadia** [comment]
I read issue #10. Just a small concern I get when reading that issue: By default, the controls of the vehicle still should be enabled. Not that these vehicle controls gets disabled in order to prevent the cinematic camera to trigger.
