### ISSUE TITLE
Menu Instructions Overlaps with Timer Bar

### ISSUE THREAD

**Issue by 07-stadia** [LemonUIbyLemon/LemonUI#73]
**Issue:**
When LemonUI menu is open and some Timer Bar(s) is/are displayed, the Timer Bars and the instructions bar (Back, Select bar) of that menu overlaps.
**Expected behavior:**
When a LemonUI menu is open, not to overlap Timer Bar(s) by e.g. moving Timer Bar(s) up a bit.
**Environment Information**
LemonUI version: 1.7.0
RagePluginHookSDK: 1.86.1288.16169
.NET Framework: 4.7.2

**Comment by justalemon** [comment]
Menus are independent from the Timer Bars, that is up to the end developer using those UI elements to handle (for example, disable the timer bar collection when the menus are open).

**Comment by justalemon** [comment]
Also, it feels kinda related to #69

**Comment by 07-stadia** [comment]
Not sure if it was clear. But this is my issue:
![Grand Theft Auto V 25_06_2022 14_58_12-1](https://user-images.githubusercontent.com/103380751/175774497-ca936eb6-477d-4c64-8865-b5dcbcc4a41c.png)
If I'm expected to handle it, I expect a way to move the Timer Bars up myself. I can't find such method. I don't want to disable these when a menu is open. The best way I can come up is to add a blank timer bar when a menu is open.

**Comment by justalemon** [comment]
Please check #75, I think that will help with your problem :)
