### ISSUE TITLE
LemonUI namespace cant be found

### ISSUE THREAD

**Issue by BeastBomber23** [LemonUIbyLemon/LemonUI#77]
I have all the correct files in my scripts folder but I still cant use LemonUI.
![image](https://user-images.githubusercontent.com/59712082/176946410-b2df367d-ae16-47f5-a59d-4b50512318f7.png)
![image](https://user-images.githubusercontent.com/59712082/176946473-41a2d18e-0370-495e-b286-4f12223547da.png)
![image](https://user-images.githubusercontent.com/59712082/176946521-0d841431-5dfc-4e9c-a15f-1433ef9f9b18.png)
Please help. I have been trying to use it for the last day.

**Comment by justalemon** [comment]
You can't use external libraries with CS files that get compiled by ScriptHookVDotNet, you need to build a project from Visual Studio, Rider or the Command Line.

**Comment by BeastBomber23** [comment]
Ok. Thank you!

**Comment by DanschFinch** [comment]
> I have all the correct files in my scripts folder but I still cant use LemonUI. ![image](https://user-images.githubusercontent.com/59712082/176946410-b2df367d-ae16-47f5-a59d-4b50512318f7.png) ![image](https://user-images.githubusercontent.com/59712082/176946473-41a2d18e-0370-495e-b286-4f12223547da.png) ![image](https://user-images.githubusercontent.com/59712082/176946521-0d841431-5dfc-4e9c-a15f-1433ef9f9b18.png) Please help. I have been trying to use it for the last day.

**Comment by justalemon** [comment]
Again

> You can't use external libraries with CS files that get compiled by ScriptHookVDotNet, you need to build a project from Visual Studio, Rider or the Command Line.
