### ISSUE TITLE
Keybind list

### ISSUE THREAD

**Issue by BeastBomber23** [LemonUIbyLemon/LemonUI#79]
Is there currently a way to put the controls at the bottom of the screen like this?
![image](https://user-images.githubusercontent.com/59712082/177608853-99dcad5f-73d1-4b21-9841-6078ebfa69e7.png)

**Comment by justalemon** [comment]
[Instructional Buttons](https://github.com/LemonUIbyLemon/LemonUI/blob/master/LemonUI/Scaleform/InstructionalButtons.cs)
