### ISSUE TITLE
Failed to compile script

### ISSUE THREAD

**Issue by Linusen9** [LemonUIbyLemon/LemonUI#80]
(Probably my bad coding "skills") When I try to use LemonUI it doesn't show any errors in visual studio but when I go into gta and press f4 to get Script Hook V .NET 3.4.0 menu it shows 3 (before it was 5 but I "fixed it" probably in a really bad way) the Error goes:
 
Could not find type or namespace name LemonUI (missing a using directive or composition reference?)
Could not find type or namespace name LemonUI (missing a using directive or composition reference?)
Could not find type or namespace name ObjectPool (missing a using directive or composition reference?)
Could not find type or namespace name NativeMenu (missing a using directive or composition reference?)
Could not find type or namespace name NativeItem (missing a using directive or composition reference?)
(translated with google translate)

tell me if I need to post code here or not

(error message in swedish)

![image](https://user-images.githubusercontent.com/91480343/177857080-5648cf3b-6a6b-48af-b5bf-43e44d92b0ed.png)

**Comment by Linusen9** [comment]
now it says this btw
![image](https://user-images.githubusercontent.com/91480343/177857171-4b73402a-eee6-49e5-bbaf-ace120c993b9.png)

**Comment by justalemon** [comment]
Please check #77

Going to copy paste it here just in case:

> You can't use external libraries with CS files that get compiled by ScriptHookVDotNet, you need to build a project from Visual Studio, Rider or the Command Line.

**Comment by Linusen9** [comment]
Could you describe to like a stupid person (new to c#)

**Comment by justalemon** [comment]
The only way to get

> Could not find type or namespace name ,,,

Is that you didn't compiled the project and instead added the CS file to your script directory.

**Comment by justalemon** [comment]
Correct, but based on the exceptions thrown in the console, you didn't copied the output files (in this case, the DLL and PDB files).

**Comment by Linusen9** [comment]
Someone should make like a tutorial on lemonui because there are like thousands of tutorials on native ui and like really old too (2019/2020 newest one I’ve seen is 2021)

**Comment by Linusen9** [comment]
Do I have the C# script file in the scripts folder

**Comment by Linusen9** [comment]
and how do I add it with nuget?

**Comment by Linusen9** [comment]
![image](https://user-images.githubusercontent.com/91480343/177957526-c763c563-e91b-4a15-b6f9-f90166785a98.png)
It should look like that?

**Comment by Linusen9** [comment]
still got the errors
