### ISSUE TITLE
NativeStatsPanel aspect ratio bug

### ISSUE THREAD

**Issue by SkyZ0347** [LemonUIbyLemon/LemonUI#93]
From what i tested, having different resolution than 16:9 (1920x1080 / 1280/720) moves **NativeStatsPanel** more to the right,
Just to mention it's happening on every screen type, (windowed, fullscreen, windowed borderless) but it's kinda obvious.

Here are examples of how it looks on 16:9 (1280x720 windowed) and 4:3 (1280x1024 also windowed):
![image](https://user-images.githubusercontent.com/87867345/189543582-f364aa17-b431-4d03-8088-1d7f0315a410.png)
![image](https://user-images.githubusercontent.com/87867345/189543605-726be5d8-41d3-4509-a910-bd6eecee2402.png)

I know it's kinda small difference but it's very noticable and I'll be really thankful for fixing it.

**Comment by justalemon** [comment]
I took the time to rewrite the source code that deals with the recalculation of the NativeStatsPanel and NativeStatsInfo. This is what it looks like right now:

16:9 Maximum Safe Zone
![image](https://user-images.githubusercontent.com/11861253/197696878-721ce2f9-0b19-43c0-9269-ef7ebf4cb3db.png)

16:9 Minimum Safe Zone
![image](https://user-images.githubusercontent.com/11861253/197697395-23a5ec95-8fdd-491a-ad65-a89c2f365fcb.png)

4:3 Maximum Safe Zone
![image](https://user-images.githubusercontent.com/11861253/197697091-a9bbc96e-16e1-4154-98f4-9a91b9f2a5dd.png)

4:3 Minimum Safe Zone
![image](https://user-images.githubusercontent.com/11861253/197697257-03236bf2-34a7-40d0-ae03-da29fd8fb134.png)
