### ISSUE TITLE
Switching From Native To Lemon

### ISSUE THREAD

**Issue by KSJDiamondGaming** [LemonUIbyLemon/LemonUI#94]
![LemonUi](https://user-images.githubusercontent.com/83096833/192858502-34287cc9-2503-4244-bbbd-cf1ee8eb12e8.png)

Tried to switch Native Events with LemonUi and got errors. So have resorted to default for now. Any assistance switching please.

**Comment by justalemon** [comment]
LemonUI is currently only available for Mono projects (C#, VB.net and F#), not for Lua.

There is a Lua version in the works, you can check the progress [LemonUIbyLemon/LemonUI_Lua](https://github.com/LemonUIbyLemon/LemonUI_Lua). There is nothing yet implemented but you might want to follow the repo to learn when it's finally release :)
